# -*- coding: utf-8 -*-
"""Monthly Sales Trend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfNPUz05o9QOg8mgVGt6dqaRBfXoyhYL
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

# Read Excel file
df = pd.read_excel("Sample - Superstore.xlsx")

# Convert Order Date to datetime
df["Order Date"] = pd.to_datetime(df["Order Date"])

# Group sales by month
monthly_sales = (
    df.groupby(df["Order Date"].dt.to_period("M"))["Sales"]
    .sum()
    .reset_index()
)

# Convert period to datetime
monthly_sales["Order Date"] = monthly_sales["Order Date"].dt.to_timestamp()

# Display monthly table
print(monthly_sales)

# Create line chart
plt.figure(figsize=(12, 6))

plt.plot(
    monthly_sales["Order Date"],
    monthly_sales["Sales"],
    marker="o"
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()